### ISSUE TITLE
Very good initiative + links

### ISSUE THREAD

**Issue by lrq3000** [jaap-karssenberg/zim-android-mockapp#1]
Not an issue but just a +1 for the initiative!

There were also other attempts at making an Android port for Zim. I didn't try them by myself but they may be worth a look:
- https://github.com/kcg/Zim4A
- https://github.com/hansihe/ZimDroid
- https://github.com/prahal/ZimDroid

Good luck, I really hope this project will work out!

**Comment by jaap-karssenberg** [comment]
Please use the wiki instead of issue tracker for notes: https://github.com/jaap-karssenberg/zim-android-mockapp/wiki

**Comment by lrq3000** [comment]
If you authorize me (github's permissions), then yes, I'll do it :)

**Comment by jaap-karssenberg** [comment]
I was in the understanding that it was public already, but apparently it
wasn't. Should be publicly editable now.

Regards,

Jaap

**Comment by lrq3000** [comment]
It's public now, thank you, I will contribute :) (I will put the links to the previous attempts there, tell me if you disagree)
