### ISSUE TITLE
Using Zimdroid as the current Zim android app

### ISSUE THREAD

**Issue by ghost** [jaap-karssenberg/zim-android-mockapp#2]
Zimdroid seems to be a potential app for zim, at least for the forseeable future. it is coded in java. Ive tested it successfully with syncthing and my main zim install and it already has editing and viewing capabilities. All we would need to do is modernize it and and some other features. https://launchpad.net/zimdroid. If you have the time, email me so we can discuss this because i want to help in any way i can

**Comment by jessewriter** [comment]
ghost is it possible to package zimdroid up as an apk so that I can test it on my nexus 5x?  I may be interested in contributing to this project once I get some down time from my busy work.  Thank you guys for everything Zim is an awesome tool on my desktop!

**Comment by s3rgi** [comment]
I have used zim desktop for 4 months and I love this application! It would be wonderful if there was an Android application. I am not a programmer, but I would be happy to be a beta tester as soon as there is a mobile version!

Thanks for this fantastic application !

**Comment by jaap-karssenberg** [comment]
Please see rationale for wanting to stick to python in the wiki page. I'm open for other implementations, but I won't work on those myself.
